### ISSUE TITLE
Time to beat and image

### ISSUE THREAD

**Issue by RFlintstone** [enisz/igdb#1]
How do I request time to beat info and logos/thumbnails from the game?
I'm working on a project where I need to request this data,

-Ruben

**Comment by enisz** [comment]
Hi Ruben,

These two values are part of the response of the game endpoint. You can easily fetch this information.

```
<?php

    require 'src/class.igdb.php';

    // Instantiate the class
    $IGDB = new IGDB('<YOUR API KEY>');

    // Setting up the query parameters
    $options = array(
        'search' => 'uncharted 4', // searching for uncharted 4
        'fields' => array(
            'id',
            'name',
            'cover', // Cover images
            'time_to_beat', // Time to beat information
            'screenshots', // Screenshots
            'artworks' // Artworks
        )
    );

    try
    {
        // Running the query against IGDB; passing the options parameter
        $result = $IGDB->game($options);

        // Showing the result
        var_dump($result);   
    }

    catch (Exception $e)
    {
        // Catching Exceptions, if there is any
        echo $e->getMessage();
    }

?>
```

The script above will return with a few games. You can get exactly only one match if you know the ID of the game already and use the ID parameter in the options array instead of the SEARCH. Please refer to the Readme regarding the behaviour.

The output for Uncharted 4 will be the following:

```
object(stdClass)[2]
  public 'id' => int 7331
  public 'name' => string 'Uncharted 4: A Thief's End' (length=26)
  public 'time_to_beat' => 
    object(stdClass)[3]
      public 'hastly' => int 50460
      public 'normally' => int 62268
      public 'completely' => int 61200
  public 'screenshots' => 
    array (size=5)
      0 => 
        object(stdClass)[4]
          public 'url' => string '//images.igdb.com/igdb/image/upload/t_thumb/fn1wbuvikoacxt4zvfxl.jpg' (length=68)
          public 'cloudinary_id' => string 'fn1wbuvikoacxt4zvfxl' (length=20)
          public 'width' => int 1920
          public 'height' => int 1080
      1 => 
        object(stdClass)[5]
          public 'url' => string '//images.igdb.com/igdb/image/upload/t_thumb/b41umzxjcehm8fozl3gf.jpg' (length=68)
          public 'cloudinary_id' => string 'b41umzxjcehm8fozl3gf' (length=20)
          public 'width' => int 1920
          public 'height' => int 1080
      2 => 
        object(stdClass)[6]
          public 'url' => string '//images.igdb.com/igdb/image/upload/t_thumb/qwytrspu8brvow9x9y15.jpg' (length=68)
          public 'cloudinary_id' => string 'qwytrspu8brvow9x9y15' (length=20)
          public 'width' => int 1920
          public 'height' => int 1080
      3 => 
        object(stdClass)[7]
          public 'url' => string '//images.igdb.com/igdb/image/upload/t_thumb/rtu8k7vm5x4mw5hilh2z.jpg' (length=68)
          public 'cloudinary_id' => string 'rtu8k7vm5x4mw5hilh2z' (length=20)
          public 'width' => int 1920
          public 'height' => int 1080
      4 => 
        object(stdClass)[8]
          public 'url' => string '//images.igdb.com/igdb/image/upload/t_thumb/tqt0sxjytiovh3g96cl0.jpg' (length=68)
          public 'cloudinary_id' => string 'tqt0sxjytiovh3g96cl0' (length=20)
          public 'width' => int 1920
          public 'height' => int 1080
  public 'artworks' => 
    array (size=5)
      0 => 
        object(stdClass)[9]
          public 'url' => string '//images.igdb.com/igdb/image/upload/t_thumb/ar4v7.jpg' (length=53)
          public 'cloudinary_id' => string 'ar4v7' (length=5)
          public 'width' => int 1500
          public 'height' => int 1060
      1 => 
        object(stdClass)[10]
          public 'url' => string '//images.igdb.com/igdb/image/upload/t_thumb/ar4v6.jpg' (length=53)
          public 'cloudinary_id' => string 'ar4v6' (length=5)
          public 'width' => int 1500
          public 'height' => int 1060
      2 => 
        object(stdClass)[11]
          public 'url' => string '//images.igdb.com/igdb/image/upload/t_thumb/ar4v5.jpg' (length=53)
          public 'cloudinary_id' => string 'ar4v5' (length=5)
          public 'width' => int 1500
          public 'height' => int 1060
      3 => 
        object(stdClass)[12]
          public 'url' => string '//images.igdb.com/igdb/image/upload/t_thumb/ar4v4.jpg' (length=53)
          public 'cloudinary_id' => string 'ar4v4' (length=5)
          public 'width' => int 1500
          public 'height' => int 1059
      4 => 
        object(stdClass)[13]
          public 'url' => string '//images.igdb.com/igdb/image/upload/t_thumb/ar4v3.jpg' (length=53)
          public 'cloudinary_id' => string 'ar4v3' (length=5)
          public 'width' => int 1500
          public 'height' => int 1059
  public 'cover' => 
    object(stdClass)[14]
      public 'url' => string '//images.igdb.com/igdb/image/upload/t_thumb/zvkdiv2dze8tcit6bzza.jpg' (length=68)
      public 'cloudinary_id' => string 'zvkdiv2dze8tcit6bzza' (length=20)
      public 'width' => int 800
      public 'height' => int 960
```

In this object you will have every requested data. Also please refer to the IGDB Documentation to get a better understanding of the data you are working with:

[Endpoints > Game](https://igdb.github.io/api/endpoints/game/)
[Miscellaneous objects > Image](https://igdb.github.io/api/misc-objects/image/)
[Miscellaneous objects > Time to beat](https://igdb.github.io/api/misc-objects/time-to-beat/)
[Reference > Images](https://igdb.github.io/api/references/images/)

Cheers!

**Comment by RFlintstone** [comment]
And if I want to echo the time, artwork or screenshot?

Will that be something in the term like `$result->artworks[0]`?

-Ruben

**Comment by enisz** [comment]
The results are returned as an array of objects. In this example the screenshot, artworks and covers are also arrays.

So if you want to use the values of them:

time_to_beat:
```
$result[0]->time_to_beat->hastly
```

screenshot, artworks
```
$result[0]->screenshots[0]->url
$result[0]->artworks[0]->url
```

cover
```
$result[0]->cover->url
```

You can see every field's return type in the game endpoint documentation.

**Comment by RFlintstone** [comment]
> The results are returned as an array of objects. In this example the screenshot, artworks and covers are also arrays.
> 
> So if you want to use the values of them:
> 
> time_to_beat:
> 
> ```
> $result[0]->time_to_beat->hastly
> ```
> screenshot, artworks
> 
> ```
> $result[0]->screenshots[0]->url
> $result[0]->artworks[0]->url
> ```
> cover
> 
> ```
> $result[0]->cover->url
> ```
> You can see every field's return type in the game endpoint documentation.

Weird, it doesn't seem to work for me. I get the following error:
`Fatal error: Uncaught Error: Cannot use object of type stdClass as array in D:\xampp\htdocs\studie\Jaar 2\Onderhouden en Beheren\igdb node official\index.php:33 Stack trace: #0 {main} thrown in D:\xampp\htdocs\studie\Jaar 2\Onderhouden en Beheren\igdb node official\index.php on line 33`

On line 33:
`        echo "Cover: " . $result[0]->cover->url;`

**Comment by enisz** [comment]
Yes, it seems there was some bug with the error handling when a bad request was done. I just pushed an updated version to the master branch. Download that source and try your request once more.

If it still fails, copy your code where you create and parameterise the $options array.

**Comment by RFlintstone** [comment]
Hi, it failed again after I cloned your master git in a new project.

Code: https://hastebin.com/qamexosuwe.xml

-Ruben

**Comment by RFlintstone** [comment]
Hi, it failed again after I cloned your master git in a new project.
(`git clone https://github.com/enisz/igdb`)

Code: https://hastebin.com/ovovikizis.xml

-Ruben

**Comment by enisz** [comment]
I have checked your code and you are facing this issue because not every game has time_to_beat property. Check out your results with only the id, name and time_to_beat details:

```
object(stdClass)[2]
  public 'id' => int 1026
  public 'name' => string 'The Legend of Zelda: A Link to the Past' (length=39)
  public 'time_to_beat' => 
    object(stdClass)[3]
      public 'hastly' => int 0
      public 'normally' => int 0
      public 'completely' => int 0
object(stdClass)[4]
  public 'id' => int 41825
  public 'name' => string 'The Legend of Zelda: Breath of the Wild - The Master Trials' (length=59)
object(stdClass)[5]
  public 'id' => int 41826
  public 'name' => string 'The Legend of Zelda: Breath of the Wild - The Champions' Ballad' (length=63)
object(stdClass)[6]
  public 'id' => int 44030
  public 'name' => string 'The Legend of Zelda Majora's Mask 3D Limited Edition' (length=52)
object(stdClass)[7]
  public 'id' => int 89904
  public 'name' => string 'The Legend of Zelda Ocarina of Time 3D (First Edition)' (length=54)
```

From this you can clearly see that the game with id 1026 is the only one which has this property. In every iteration of your loop you have to make sure that the given property exists. You should update your code like this:

```
<?php

    require 'igdb/src/class.igdb.php';

    $IGDB = new IGDB('API KEY');

    $options = [
        'search' => 'zelda',
        'fields' => [
            'id',
            'name',
            'cover',
            'time_to_beat',
            'screenshots',
            'artworks'
        ],
        'limit' => 5,
        'offset' => 10,
    ];

    try {
        $results = $IGDB->game($options);

        foreach ($results as $result) {
            if(property_exists($result, 'time_to_beat')) // Check if the time_to_beat property exists in the $result object
                echo $result->time_to_beat->hastly . '<br/>';
            else
                echo 'No time to beat information!' . '<br/>';
        }
    } catch (Exception $e) {
        echo $e->getMessage();
    }

?>
```
Note that there is an if statement in the first line of the for loop which checks if the given property exists. With the code above the expected output is:
```
0
No time to beat information!
No time to beat information!
No time to beat information!
No time to beat information!
```
You should check out the IGDB Documentation regarding the mandatory fields to know which values should be checked before accessing them.

**Comment by RFlintstone** [comment]
It doesn't seem to find the time to beat data where it is clearly there on `igdb.com` itself.

Code: https://hastebin.com/isogutuwoq.xml

-Ruben

**Comment by enisz** [comment]
I have compared a few of the results from the code with the IGDB site, but I could see the same results in my code and on the site.

Please provide a few game id's or names where you can see time to beat data but in the code it is not there.

**Comment by RFlintstone** [comment]
Here is the example:
https://hastebin.com/evupakerip.xml
(Search for The Legend of Zelda: Breath of the Wild)

IGDB Page:
https://www.igdb.com/games/the-legend-of-zelda-breath-of-the-wild

**Comment by RFlintstone** [comment]
Here is the example:
https://hastebin.com/atohizeyeg.xml
(Search for The Legend of Zelda: Breath of the Wild)

IGDB Page:
https://www.igdb.com/games/the-legend-of-zelda-breath-of-the-wild

**Comment by enisz** [comment]
The ID of The Legend of Zelda: Breath of the Wild is 7346. I'm using the following code:

```
<?php

    require 'src/class.igdb.php';

    $IGDB = new IGDB('API KEY');

    $options = [
        'id' => 7346,
        'fields' => [
            'id',
            'name',
            'time_to_beat',
        ]
    ];

    var_dump($IGDB->game($options));

?>
```

The output of the code is this:

```
array (size=1)
  0 => 
    object(stdClass)[2]
      public 'id' => int 7346
      public 'name' => string 'The Legend of Zelda: Breath of the Wild' (length=39)
      public 'time_to_beat' => 
        object(stdClass)[3]
          public 'hastly' => int 156600
          public 'normally' => int 363600
          public 'completely' => int 590400
```

The time to beat data is clearly there.

**Comment by RFlintstone** [comment]
I will try that soon. Is there a way to convert a game name to an ID?

**Comment by enisz** [comment]
Not that I know of. I ran a query with search = the legend of zelda and I got the ID from there to have only this record in the output for better visibility.

When I was using search, it had the same output.

**Comment by RFlintstone** [comment]
> Not that I know of. I ran a query with search = the legend of zelda and I got the ID from there to have only this record in the output for better visibility.
> 
> When I was using search, it had the same output.

Hmm, weird, what was your code while testing?

**Comment by enisz** [comment]
```
<?php

    require 'src/class.igdb.php';

    $IGDB = new IGDB('api key');

    $options = [
        'search' => 'the legend of zelda',
        'fields' => [
            'id',
            'name',
            'time_to_beat',
        ],
        'limit' => 50
    ];

    var_dump($IGDB->game($options));

?>
```
From the output of this I could find the exact ID for the game you said.
