### ISSUE TITLE
Time to beat

### ISSUE THREAD

**Issue by annikaheppner** [enisz/igdb#23]
Hey, I noticed that the time_to_beat field has been removed from the games endpoint. How can I access this data now, given a game ID?

**Comment by enisz** [comment]
Hi @annikaheppner,

According to the IGDB documentation, in the [Breaking Changes](https://api-docs.igdb.com/#breaking-changes) section the time_to_beat data is marked as removed. You are not able to fetch these data from the API anymore. However, there is a downloadable csv file which contains some data if it helps.

https://d2ssegy8jiabys.cloudfront.net/time_to_beats.csv
